# Generated by Django 6.0.4 on 2026-04-15 17:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='resume_analyzer_application.resume', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])]),
        ),
    ]
