# Generated by Django 6.0.4 on 2026-04-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0002_alter_jobdescription_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='resumeanalysis',
            options={'ordering': ['-created_at']},
        ),
    ]
