# Generated by Django 6.0.4 on 2026-04-27 18:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0003_alter_resume_options_alter_resumeanalysis_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resume', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='resume_analyzer_application.resume'),
        ),
    ]
