# Generated by Django 6.0.4 on 2026-05-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0004_alter_resume_file_alter_resumeanalysis_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
