# Generated by Django 6.0.4 on 2026-05-02 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0005_jobdescription_company_name_jobdescription_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
