# Generated by Django 6.0.4 on 2026-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0006_jobdescription_created_at_jobdescription_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='tags',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
