# Generated by Django 6.0.4 on 2026-05-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0007_alter_jobdescription_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='tags',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
