# Generated by Django 6.0.4 on 2026-05-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0008_alter_jobdescription_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='score_breakdown',
            field=models.JSONField(default=list),
        ),
    ]
