# Generated by Django 6.0.4 on 2026-05-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0009_resumeanalysis_score_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='matching_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
