# Generated by Django 6.0.4 on 2026-05-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0010_resumeanalysis_matching_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='matching_rate',
            new_name='matching_rates',
        ),
    ]
