# Generated by Django 6.0.4 on 2026-05-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0011_rename_matching_rate_resumeanalysis_matching_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='matching_rates',
            field=models.CharField(default='Poor Matching'),
        ),
    ]
