# Generated by Django 6.0.4 on 2026-05-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0012_alter_resumeanalysis_matching_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
