# Generated by Django 6.0.4 on 2026-05-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0013_subscription_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'FREE'), ('pro', 'PRO'), ('enterprise', 'ENTERPRISE')], default='free', max_length=100),
        ),
    ]
