# Generated by Django 6.0.4 on 2026-05-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0015_alter_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(blank=True, default='free', max_length=200),
        ),
    ]
