# Generated by Django 6.0.4 on 2026-05-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0016_alter_user_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at']},
        ),
    ]
