# Generated by Django 6.0.4 on 2026-05-26 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer_application', '0017_alter_subscription_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('resume_upload', 'Resume Upload'), ('resume_analysis', 'Resume Analysis'), ('job_description', 'Job Description Added'), ('re_analysis', 'Re-Analysis')], max_length=50)),
                ('resource', models.CharField(max_length=255)),
                ('credits_used', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('processing', 'Processing'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
